platform :ios ,'8.0'

target '掌上优医'do

pod 'JSONModel', '~> 1.8.0' #model
pod 'AFNetworking', '~> 3.2.1'  #网络
pod 'Masonry', '~> 1.1.0'   #布局
pod 'SDWebImage'    #图片
pod 'IQKeyboardManager', '~> 6.2.0' #键盘
pod 'MJRefresh', '~> 3.1.15.7' #上下拉
pod 'SVProgressHUD', '~> 2.2.5'
pod 'YYCategories'
pod 'YYCache'
pod 'MWPhotoBrowser', '~> 2.1.2'
pod 'AliyunOSSiOS'
pod 'AMapLocation-NO-IDFA' #无IDFA版定位 SDK
pod 'AMap2DMap-NO-IDFA' #2D地图SDK (2D和3D不能同时使用)
pod 'AMapSearch-NO-IDFA'

pod 'UMCCommon'
pod 'UMCAnalytics'
#pod 'UMCShare/Social/WeChat'

pod 'JPush'

pod 'JXCategoryView'

pod 'ASIHTTPRequest', '~> 1.8.2'

pod 'SCIndexView'

pod 'UINavigation-SXFixSpace'

#pod 'Weibo_SDK', :git => 'https://github.com/sinaweibosdk/weibo_ios_sdk.git'

#pod 'SSZipArchive', '~> 1.1'

#pod 'UMCCommon-NO-IDFA'
#pod 'UMCAnalytics_no-idfa'
#pod 'UMCSecurityPlugins-NO-IDFA'
#pod 'UMengAnalytics-NO-IDFA'

end
